### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by mricanho**
In this milestone, we created a model with associations and all requested features for friendships. Plus, we configured RSpec and create a test for the friendship integration.

### CODE REVIEW

**Comment by mricanho** [comment]
I don't really know why adding some gems is making a conflict, but once the code reviewer approved the merge, we will merge it from the command line.

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**Good job on your project 👏. Check the mandatory requirements below.**

### Highlights

1). **You don't have logic in your views.**

### Mandatory requirements

1). **Users should not see each other's posts unless they are confirmed friends.**

2). **A logged-in user should not be able to send themselves a friend request. For example, if I am logged in as Jen, I should not have an "Invite to Friendship" button next to my name in the users' list page or my profile.**

3). **Say Jen is logged in and decides to send Mercy a friend request. After Jen clicks the button, the button should switch to a text informing the user that the friend request has been sent. See an example in the screenshot below.**

 before a request is sent  | After a request is sent
 ---------------------------| ------------------------
before_request | after_request

4). **A user should be able to see friendship requests received. Using the example above, when Mercy logs in, she should see an accept button and reject button for Jen's friendship request. See an example in the screenshot below.**

mercyprofile


5). **The friend request button should also be added to a user's profile page. As shown in the example below, a logged-in user is able to see a friend request button when they visit Dan's profile.**

danprofile

6). **Write unit tests for all your files in the `app/models` directory.**
7). **Write unit tests for your views.**
8). **Remove `if` logic in `layouts/application.html.erb` file.**

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Miguel Ricaño Romero & Kanhai Kanhai** 
Nice job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a few details to improve before you can go ahead:

- [x] Add a screenshot in the README file
- [x] Your friendships_request_spec.rb file doesn't have any test, it should be removed
- [x] Don't overuse rubocop disable
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @mricanho and @harshdeepkanhai ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
